// <auto-generated />
using System;
using BoardGameReviewsBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoardGameReviewsBackend.Migrations.Migrations
{
    [DbContext(typeof(BoardgamesDbContext))]
    [Migration("20250424123204_CreatedReviews")]
    partial class CreatedReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.Boardgame", b =>
                {
                    b.Property<int>("boardgameid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("boardgameid"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("nrOfPlayers")
                        .HasColumnType("integer");

                    b.Property<int?>("playTime")
                        .HasColumnType("integer");

                    b.Property<int?>("weight")
                        .HasColumnType("integer");

                    b.HasKey("boardgameid");

                    b.ToTable("Boardgames");
                });

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.Review", b =>
                {
                    b.Property<int>("reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("reviewId"));

                    b.Property<int>("boardgameId")
                        .HasColumnType("integer");

                    b.Property<string>("message")
                        .HasColumnType("text");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("reviewId");

                    b.HasIndex("boardgameId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.Review", b =>
                {
                    b.HasOne("BoardGameReviewsBackend.Data.Models.Boardgame", "boardgame")
                        .WithMany("Reviews")
                        .HasForeignKey("boardgameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("boardgame");
                });

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.Boardgame", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
