// <auto-generated />
using System;
using BoardGameReviewsBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoardGameReviewsBackend.Migrations.Migrations
{
    [DbContext(typeof(BoardgamesDbContext))]
    [Migration("20250527080648_AddedEmailToBoardgame")]
    partial class AddedEmailToBoardgame
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.Boardgame", b =>
                {
                    b.Property<int>("boardgameid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("boardgameid"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("nrOfPlayers")
                        .HasColumnType("integer");

                    b.Property<int?>("playTime")
                        .HasColumnType("integer");

                    b.Property<double?>("weight")
                        .HasColumnType("double precision");

                    b.HasKey("boardgameid");

                    b.ToTable("Boardgames");

                    b.HasData(
                        new
                        {
                            boardgameid = 1,
                            Category = "Abstract",
                            Description = "Decorate a palace ceiling after creating your own pattern.",
                            Image = "/azul_duel.jpg",
                            ReleaseDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Azul Duel",
                            nrOfPlayers = 2,
                            playTime = 60,
                            weight = 2.2000000000000002
                        },
                        new
                        {
                            boardgameid = 2,
                            Category = "Strategy",
                            Description = "Explore an island, discover artifacts, and defeat guardians.",
                            Image = "/lost_ruins_of_arnak.jpg",
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Lost Ruins of Arnak",
                            nrOfPlayers = 1,
                            playTime = 120,
                            weight = 2.5
                        },
                        new
                        {
                            boardgameid = 3,
                            Category = "Strategy",
                            Description = "Influence, intrigue, and combat in the universe of Dune.",
                            Image = "/dune_imperium.jpg",
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Dune Imperium",
                            nrOfPlayers = 1,
                            playTime = 120,
                            weight = 3.0
                        },
                        new
                        {
                            boardgameid = 4,
                            Category = "Abstract",
                            Description = "Sew a quilt, collect buttons, attract cats!",
                            Image = "/calico.jpg",
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Calico",
                            nrOfPlayers = 4,
                            playTime = 45,
                            weight = 1.8
                        },
                        new
                        {
                            boardgameid = 5,
                            Category = "Cooperative",
                            Description = "Mutating diseases are spreading around the world - can your team save humanity?",
                            Image = "/pandemic_legacy.jpg",
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Pandemic Legacy",
                            nrOfPlayers = 2,
                            playTime = 60,
                            weight = 3.5
                        },
                        new
                        {
                            boardgameid = 6,
                            Category = "Cooperative",
                            Description = "Complete missions in space in this cooperative trick-taking game.",
                            Image = "/the_crew.jpg",
                            ReleaseDate = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "The Crew",
                            nrOfPlayers = 2,
                            playTime = 30,
                            weight = 2.0
                        },
                        new
                        {
                            boardgameid = 7,
                            Category = "Family",
                            Description = "In this competitive real estate market, there's only one possible outcome: Monopoly!",
                            Image = "/monopoly.jpg",
                            ReleaseDate = new DateTime(1935, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Monopoly",
                            nrOfPlayers = 4,
                            playTime = 90,
                            weight = 1.0
                        },
                        new
                        {
                            boardgameid = 8,
                            Category = "Party",
                            Description = "Give your team clever one-word clues to help them spot their agents in the field.",
                            Image = "/codenames.jpg",
                            ReleaseDate = new DateTime(2015, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Codenames",
                            nrOfPlayers = 4,
                            playTime = 30,
                            weight = 1.5
                        },
                        new
                        {
                            boardgameid = 9,
                            Category = "Strategy",
                            Description = "Collect and trade resources to build up the island of Catan in this modern classic.",
                            Image = "/catan.jpg",
                            ReleaseDate = new DateTime(1995, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Catan",
                            nrOfPlayers = 3,
                            playTime = 90,
                            weight = 2.0
                        });
                });

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.Log", b =>
                {
                    b.Property<int>("logId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("logId"));

                    b.Property<string>("actionPerformed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("logId");

                    b.HasIndex("userId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.MonitoredUser", b =>
                {
                    b.Property<int>("monitoredId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("monitoredId"));

                    b.Property<DateTime>("monitoredSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("monitoredId");

                    b.HasIndex("userId");

                    b.ToTable("MonitoredUsers");
                });

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.Review", b =>
                {
                    b.Property<int>("reviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("reviewId"));

                    b.Property<int>("boardgameId")
                        .HasColumnType("integer");

                    b.Property<string>("message")
                        .HasColumnType("text");

                    b.Property<int>("rating")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("reviewId");

                    b.HasIndex("boardgameId");

                    b.HasIndex("userId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            reviewId = 1,
                            boardgameId = 1,
                            message = "Amazing game!",
                            rating = 5,
                            userId = 2
                        },
                        new
                        {
                            reviewId = 2,
                            boardgameId = 2,
                            message = "Great design, but a bit complex.",
                            rating = 4,
                            userId = 3
                        },
                        new
                        {
                            reviewId = 3,
                            boardgameId = 3,
                            message = "Fun but repetitive.",
                            rating = 3,
                            userId = 2
                        },
                        new
                        {
                            reviewId = 4,
                            boardgameId = 6,
                            message = "Perfect for quick games!",
                            rating = 5,
                            userId = 3
                        },
                        new
                        {
                            reviewId = 5,
                            boardgameId = 7,
                            message = "Classic and fun.",
                            rating = 4,
                            userId = 2
                        },
                        new
                        {
                            reviewId = 6,
                            boardgameId = 9,
                            message = "Love the strategy!",
                            rating = 5,
                            userId = 3
                        },
                        new
                        {
                            reviewId = 7,
                            boardgameId = 8,
                            message = "Great for parties.",
                            rating = 4,
                            userId = 2
                        },
                        new
                        {
                            reviewId = 8,
                            boardgameId = 5,
                            message = "Not a fan.",
                            rating = 2,
                            userId = 3
                        },
                        new
                        {
                            reviewId = 9,
                            boardgameId = 1,
                            message = "Absolutely amazing!",
                            rating = 5,
                            userId = 1
                        });
                });

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userId"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("isVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = 1,
                            email = "admin@admin.com",
                            isAdmin = true,
                            isVerified = true,
                            password = "admin123",
                            username = "admin"
                        },
                        new
                        {
                            userId = 2,
                            email = "john.doe@gmail.com",
                            isAdmin = false,
                            isVerified = true,
                            password = "123123",
                            username = "john_doe"
                        },
                        new
                        {
                            userId = 3,
                            email = "jane.smith@gmail.com",
                            isAdmin = false,
                            isVerified = false,
                            password = "password",
                            username = "jane_smith"
                        });
                });

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.Log", b =>
                {
                    b.HasOne("BoardGameReviewsBackend.Data.Models.User", "user")
                        .WithMany("Logs")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.MonitoredUser", b =>
                {
                    b.HasOne("BoardGameReviewsBackend.Data.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.Review", b =>
                {
                    b.HasOne("BoardGameReviewsBackend.Data.Models.Boardgame", "boardgame")
                        .WithMany("Reviews")
                        .HasForeignKey("boardgameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BoardGameReviewsBackend.Data.Models.User", "user")
                        .WithMany("Reviews")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("boardgame");

                    b.Navigation("user");
                });

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.Boardgame", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("BoardGameReviewsBackend.Data.Models.User", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
